skip_missing_workers: true
allow_lossy: false
# PNG
advpng: false
optipng:
  level: 2
pngcrush: false
pngout: false
pngquant: false
# JPG
jpegrecompress: false
timeout: 15
# https://github.com/toy/image_optim/issues/87
svgo: false
